### PR TITLE
Major update

### PR DESCRIPTION
**Pull request by johnpiapian**
Changes:
- Update UserClass and CourseClass as required
- Add bootstrap to create better user interface
- Handle session and other security vulnerabilities  
- Add logout functionality
- Complete User related features
- Implement Course related features

### CODE REVIEW

**Review by njigl — APPROVED** [review]
Fantastic refactoring, I tested the functionality and it works well!

**Comment by ColinMatthewsYoung** [comment]
awesome job man.

**Review by ColinMatthewsYoung — APPROVED** [review]
just realized I didnt approve haha

**Review by HB245 — APPROVED** [review]
Looks great!

**Comment by imnotdiddykong** [comment]
Impressive work! love the bootstrap theme. Functionality feels abut the same.

**Pull request merged**
