### PR TITLE
Section young

### PR DESCRIPTION
**Pull request by ColinMatthewsYoung**
Create section is working. Will probably need to change a few things around but the bare bones should be a good start.

### CODE REVIEW

**Comment by johnpiapian** [comment]
Good job. Are we going to have separate models for class and lab now? I thought you were going to keep section and then add ta field which could be null.

**Comment by ColinMatthewsYoung** [comment]
> Good job. Are we going to have separate models for class and lab now? I thought you were going to keep section and then add ta field which could be null.

Im adding a field to the class model now, the way Humraj made the template had changing the section model to class. Just wanted to get something up and running.

**Review by njigl — APPROVED** [review]
Looks good!

**Review by johnpiapian — APPROVED** [review]
Seems to be missing the template but other than everything seems good to go

**Review by HB245 — APPROVED** [review]
looks great

**Review by imnotdiddykong — APPROVED** [review]
great job!

**Pull request merged**
